export const images = {
  // Authentication Images
  Splash: require("./SplashScreen/Splash.gif"),

  AnimationLoader:require("./SplashScreen/AnimationLoader.json"),
  AnimationLoderGif:require("./SplashScreen/AnimationLoderGif.gif"),
Moon :require("./Home/Moon.png"),


  Person: require("./Welcome/Person.png"),
  Logout: require("./Welcome/Logout.png"),
  Lock: require("./Welcome/Lock.png"),
  eyeOpen: require("./Welcome/eyeOpen.png"),
  CloseEye: require("./Welcome/CloseEye.png"),
  Email: require("./Welcome/Email.png"),
  WelcomeIcon: require("./Welcome/WelcomeIcon.png"),
  WelcomeIconWhite: require("./Welcome/WelcomeIconWhite.png"),
  Phone: require("./Welcome/Phone.png"),
  Google: require("./Welcome/Google.png"),
  library_music: require("./Bottom/library_music.png"),
  library_musicF: require("./Bottom/library_musicF.png"),
  FSearch: require("./Bottom/FSearch.png"),
  home: require("./Bottom/home.png"),
  USearch: require("./Bottom/USearch.png"),
  homeF: require("./Bottom/homeF.png"),
  BellIcon: require("./Home/BellIcon.png"),
  Profile: require("./Home/Profile.png"),
  walkthroughImg: require("./Home/walkthroughImg.png"),
  play_arrow: require("./Home/play_arrow.png"),
  Recently1: require("./Home/Recently1.png"),
  Recently2: require("./Home/Recently2.png"),
  Recently3: require("./Home/Recently3.png"),
  Mix1: require("./Home/Mix1.png"),
  Mix2: require("./Home/Mix2.png"),
  PlayBtn: require("./Home/PlayBtn.png"),
  more_vert: require("./Home/more_vert.png"),
  favorite: require("./Home/favorite.png"),
  Peace: require("./Home/Peace.png"),
  Weightless: require("./Home/Weightless.png"),
  Nothing: require("./Home/Nothing.png"),
  SmallMemory: require("./Home/SmallMemory.png"),
  ChildishGambino: require("./Search/ChildishGambino.png"),
  search: require("./Search/search.png"),
  MarvinGaye: require("./Search/MarvinGaye.png"),
  Trendingartists: require("./Search/Trendingartists.png"),
  TAMIL: require("./Search/TAMIL.png"),
  INTERNATIONAL: require("./Search/INTERNATIONAL.png"),
  POP: require("./Search/POP.png"),
  HIP: require("./Search/HIP.png"),
  DANCE: require("./Search/DANCE.png"),
  COUNTRY: require("./Search/COUNTRY.png"),
  INDIE: require("./Search/INDIE.png"),
  JAZZ: require("./Search/JAZZ.png"),
  ArtistAlbum: require("./Home/ArtistAlbum.png"),
  share: require("./Home/share.png"),
  navigate_next: require("./Home/navigate_next.png"),
  YouSearch: require("./Search/YouSearch.png"),
  closeHistory: require("./Search/closeHistory.png"),
  JohnH: require("./Search/JohnH.png"),
  Misery: require("./Home/Misery.png"),
  Payphone: require("./Home/Payphone.png"),
  Animals: require("./Home/Animals.png"),
  Sugar: require("./Home/Sugar.png"),
  TheSun: require("./Home/TheSun.png"),
  queue_music:require("./Home/queue_music.png"),
  Artists:require("./Home/Artists.png"),

//  arrow_Down: require("./spotify/arrow-down.png"),
//  down_arrow: require("./spotify/down-arrow.png"),
//  hoempage:require("./spotify/homepage.png"),
//  left:require("./spotify/left.png"),
//  library:require("./spotify/library.png"),
//  next:require("./spotify/next.png"),
//  option:require("./spotify/option.png"),
//  pause:require("./spotify/pause.png"),
//  pause2:require("./spotify/pause2.png"),
//  play_button:require("./spotify/play-button.png"),
//  play:require("./spotify/play.png"),
//  playing:require("./spotify/playing.png"),
//  plus:require("./spotify/plus.png"),
//  previous:require("./spotify/previous.png"),
//  spotify:require("./spotify/spotify.png"),
//  spotify2:require("./spotify/spotify2.png"),
//  sufflie:require("./spotify/sufflie.png"),


EditIcon: require("./Home/EditIcon.png"),
playlists:require("./Home/playlists.png"),
Contrast:require("./Home/Contrast.png"),
GlobeNetwork:require("./Home/GlobeNetwork.png"),
WarningSign:require("./Home/WarningSign.png"),
};
